# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_hclust <- function(X, n, p, ZI) {
    .Call('ziLRhClust_Cpp_hclust', PACKAGE = 'ziLRhClust', X, n, p, ZI)
}

