// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/ziLRhClust.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// Cpp_hclust
Rcpp::List Cpp_hclust(Map<VectorXd> X, int n, int p, bool ZI);
RcppExport SEXP ziLRhClust_Cpp_hclust(SEXP XSEXP, SEXP nSEXP, SEXP pSEXP, SEXP ZISEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Map<VectorXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type ZI(ZISEXP);
    __result = Rcpp::wrap(Cpp_hclust(X, n, p, ZI));
    return __result;
END_RCPP
}
